### ISSUE TITLE
Expose InIDE() and InDebugger() to user

### ISSUE THREAD

**Issue by bryceschober** [kellyethridge/VBCorLib#17]
It sure would be nice to be able to reuse the `Startup.InIDE` and `InDebugger` properties, that are used internally in `CorLib.System`, but don't seem to be available to the user.

@kellyethridge Is that a quick-and-easy addition? Would it best be accomplished by Providing access to a static `Startup` object, or via new `Environment` or `System` parameters?

**Comment by kellyethridge** [comment]
The `InIDE` method can only work for the project it is defined in (in this case only `VBCorLib`) since it depends on the compiler removing the `Debug.Assert` statement. Exposing it would only return if `VBCorLib` itself was compiled or not. That doesn't seem useful in any practical sense.

As for `InDebugger` it depends on the containing process to be `VB6.exe`. So any other non-vb6 IDE or even an external `ActiveX` process run from VB6 IDE would return false. So it would be inconsistent across programming scenarios. If the `InDebugger` were to be exposed, then it would need to be noted that it only works when working in VB6 IDE and excluding an external `ActiveX` component.

**Comment by bryceschober** [comment]
Understood, I'll just close it... though I've copied your `InIDE` method for usage in my own main module.
