### ISSUE TITLE
Multiple vbp files?  What for?

### ISSUE THREAD

**Issue by BitSprocket** [kellyethridge/VBCorLib#51]
Hi Kelly,
I'm porting VBCorLib over to VBA and ran across a few questions.  FYI, all I'm doing is importing the CorLib and Fakes files into a new single project so that I can simply import those files into a VBA (MS Access) project and not need to depend on external dll files.  (My client won't let me ship dll's with my project).

All seems to be going well (with some notable exceptions that I'll forward to you soon) but what I'm curious about is that in the Sources/CorLib folder there are two distinct vbp files - one containing the word 'build' in it.  What's the difference?  I don't see anything obvious but want to make sure I'm loading up the right one to make sure I grab all the correct files.

This effort has uncovered some issues I'm sure you'll want to know about so I'll detail them in other issues when I'm finished.

**Comment by kellyethridge** [comment]
Hello,
The reason for the Build version vbp is because it already has the RELEASE compiler constant set to 1. There are optimized routines the release version uses. This is for me more than anything. I know I can just build it and everything that is needed to be set for a release version is set correctly. You may not be able to utilize the release version of the routines in your VBA conversion, so it may not be a useful vbp in your situation. Everything should still be able to work correctly using the debug version of the routines.

**Comment by BitSprocket** [comment]
Ah, I get it.  Thanks!
